export const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "/ai-morning";
export const siteUrl = "https://thuanlg-4135.github.io";
export const asset = (path) =>
  /^(https?:)?\//.test(path) ? path : `${basePath}/assets/${path}`;
export const homePath = (language) => (language === "en" ? "/en/" : "/");
export const datePath = (date, language = "vi") =>
  `${homePath(language)}${date}/`;
export const formatDate = (date, language = "vi") =>
  new Intl.DateTimeFormat(language === "en" ? "en-GB" : "vi-VN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(`${date}T12:00:00Z`));
export const words = (language) =>
  language === "en"
    ? {
        latest: "Latest edition",
        archive: "The archive",
        quick: "The quick read",
        deep: "The bigger picture",
        releases: "Release notes",
        memo: "Developer memo",
        radar: "On the radar",
        tagline: "A little AI. A better morning.",
        intro: "Your morning dose of AI, with a developer’s perspective.",
        edition: "Issue",
        minutes: "min read",
        read: "Start reading",
        inside: "In this edition",
        sources: "Sources",
        action: "Put it to work",
        new: "New in 24h",
        context: "72h context",
        remember: "One thing to take away",
        past: "More mornings, more perspective.",
        search: "Search editions, topics…",
        empty: "No editions found. Try another keyword.",
        all: "All editions",
        saved: "Saved stories",
        save: "Save story",
        unsave: "Unsave story",
        copy: "Copy link",
        copied: "Link copied",
        copyError: "Could not copy. Copy the address from your browser.",
        theme: "Color theme",
        auto: "Auto",
        light: "Light",
        dark: "Dark",
        focus: "Reading mode",
        type: "Larger text",
        skip: "Skip to content",
        progress: "Reading progress",
        do: "Worth trying",
        avoid: "Hold off on",
        finish: "You’re all caught up.",
        finishNote: "Close the tabs. Make something good.",
        home: "Back to the latest edition",
        results: "editions",
      }
    : {
        latest: "Số mới nhất",
        archive: "Bài cũ",
        quick: "Tin nhanh",
        deep: "Đọc sâu",
        releases: "Bản phát hành",
        memo: "Góc developer",
        radar: "Radar",
        tagline: "Một chút AI. Một buổi sáng hay.",
        intro: "Tin AI chọn lọc, qua góc nhìn của người làm phần mềm.",
        edition: "Số",
        minutes: "phút đọc",
        read: "Bắt đầu đọc",
        inside: "Trong số này",
        sources: "Nguồn",
        action: "Thử trong công việc",
        new: "Mới trong 24h",
        context: "Bối cảnh 72h",
        remember: "Một điều đáng nhớ",
        past: "Mỗi buổi sáng, thêm một góc nhìn.",
        search: "Tìm số báo, chủ đề…",
        empty: "Chưa tìm thấy số báo. Thử từ khóa khác nhé.",
        all: "Tất cả",
        saved: "Bài đã lưu",
        save: "Lưu bài",
        unsave: "Bỏ lưu",
        copy: "Sao chép liên kết",
        copied: "Đã chép liên kết",
        copyError:
          "Chưa sao chép được. Bạn có thể chép địa chỉ từ trình duyệt.",
        theme: "Giao diện",
        auto: "Tự động",
        light: "Sáng",
        dark: "Tối",
        focus: "Chế độ đọc",
        type: "Tăng cỡ chữ",
        skip: "Bỏ qua điều hướng",
        progress: "Tiến độ đọc",
        do: "Nên thử",
        avoid: "Chưa nên",
        finish: "Vậy là bắt kịp rồi.",
        finishNote: "Gấp báo lại. Bắt tay làm điều hay.",
        home: "Về số mới nhất",
        results: "số báo",
      };
